// Public extension API. Applications and plugins must share one SDK instance.
export type { AdminPlugin, AdminRouteDefinition } from './admin-plugins/plugin'
export { AdminPluginRegistry } from './admin-plugins/registry'
export { adminPluginRegistryKey } from './admin-plugins/context'
export { adminAccessTokenKey, adminPermissionsKey } from './admin-context'
export type { FieldDefinition, FieldOptions, FieldType, FieldTypeMetadata, ConfigField, FieldEditorTab, AdminNavigationItem } from './types/admin'
export { default as DynamicField } from './components/fields/DynamicField.vue'
export { default as DynamicFieldsForm } from './components/fields/DynamicFieldsForm.vue'
export { default as ConfigurationEditor } from './components/fields/ConfigurationEditor.vue'
export { createFieldValues, validateFieldValues, unsupportedFieldTypes, fieldEditorError, fieldErrorMessage, isMultipleField, singleValueField } from './components/fields/model'
export type { DynamicValues, DynamicFieldErrors, FieldEditorResolver } from './components/fields/model'
export { useFieldValidation } from './components/fields/use-field-validation'
export { adminRequest, adminBlob, AdminAPIError } from './api/admin-api'
export { useSelectedSite } from './composables/use-selected-site'
export type { SiteOption, SiteDetailsResponse, SiteProfile } from './types/admin'
